### ISSUE TITLE
Deterministic Address Generation

### ISSUE THREAD

**Issue by tobywoerthle** [DanielPollithy/flashwifi#3]
Java version of [getNewAddress](https://iotaledger.github.io/iota.lib.java/javadoc/jota/IotaAPI.html#getNewAddress-java.lang.String-int-int-boolean-int-boolean-) does not have ability to get new address deterministically, only JavaScript function can do this.

Need to follow https://learn.iota.org/tutorial/generating-addresses-learn-the-basics and use findTransactions to increment index until it returns null.

**Comment by tobywoerthle** [comment]
https://github.com/iotaledger/iota.lib.js/blob/master/lib/api/api.js

@method getNewAddress
api.prototype.getNewAddress = function(seed, options, callback)

**Comment by tobywoerthle** [comment]
Used findTransactionObjectsByAddresses to iterate getNewAddress until no transactions are returned. For balance checking used the last available address that has associated transactions.

Future issue to consider: slowdown of getting new address and balance check as each used address requires one extra API call.

**Comment by DanielPollithy** [comment]
Hi Toby! I think this is generally the right behaviour. How about storing the last used index?

**Comment by tobywoerthle** [comment]
@DanielPollithy Good idea, I was thinking that too. Ended up storing it unencrypted in SharedPreferences.

**Comment by tobywoerthle** [comment]
This is affecting balance retrieval as the api.getBalanceAndFormat(inAddresses...) function needs all addresses rather than just the last two as we are storing them currently. Need to re-visit this.

**Comment by tobywoerthle** [comment]
Fixed via 653f137a99b97afce093fec72e415abfb8aa2a6f
